### ISSUE TITLE
Does this example still work?

### ISSUE THREAD

**Issue by hdaggett** [beepsoft/grapesjs-react-component-example#2]
When I start the project, I just get the normal GEditor - no option for Timer component to drag in, no bell icon in the editor toolbar.

**Comment by beepsoft** [comment]
Yep, there seemed to be some problem here. I could not really figure out what what went wrong, but my guess is that it was related to my use of grapesjs-react. So I got rid of it and initialize grapesjs right in App.tsx.

Does it work for you with this fix?

**Comment by hdaggett** [comment]
Yes, thank you!
